apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: azure-vote-front-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: azure-vote-front
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
