apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: micdemo
spec:
  resourceGroupNameRef:
    name: rg-crossplane
  vnetSubnetIDRef:
    name: mic-demo-aks
  location: westeurope
  version: "1.25.6"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: true
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    namespace: crossplane
    name: micdemo
